[package]
name = "godunov-core"
version = "0.1.0"
authors = ["Jonathan Zrake <jonathan.zrake@gmail.com>"]
edition = "2018"

[dependencies]
ndarray     = "0.14"
num         = "0.3"
async-trait = "0.1"
serde       = { version = "1.0", features = ["derive"], optional = true }
